name = "atomic-url-dev"
main = "./src/index.js"
account_id = "19a745c88f8264f29c608584b7e417ab"
compatibility_date = "2022-09-22"

workers_dev = true
kv_namespaces = [
  { binding = "URL_DB", id = "", preview_id = "ca7936b380a840908c035a88d1e76584" },
]

[dev]
ip = "0.0.0.0"
local_protocol = "http"
port = 8787
upstream_protocol = "https"

[env.staging]
name = "atomic-url-staging"
workers_dev = true
kv_namespaces = [
  { binding = "URL_DB", id = "ca7936b380a840908c035a88d1e76584" },
]

[env.production]
name = "atomic-url"
route = "s.jerrynsh.com/*"
workers_dev = false
kv_namespaces = [
  { binding = "URL_DB", id = "7da8f192d2c1443a8b2ca76b22a8069f" },
]
