name = "cf-url-shortener-dev"
type = "webpack"

account_id = "19a745c88f8264f29c608584b7e417ab"
compatibility_date = "2021-12-26"
route = ""
workers_dev = true
zone_id = "e69d9e8116a9787a7c36dc16f6195ae2"

kv_namespaces = [
  {binding = "URL_DB", id = "99043a043bf9431aa051f9c57847ce9d", preview_id = "74cf0f04b0f1402a8aab8b60abeec8e7"},
]

[env.production]
kv_namespaces = [
  {binding = "URL_DB", id = "d5ec2cc1ec3f485291700276b99fa225"},
]
name = "cf-url-shortener"
route = "s.jerrynsh.com/*"
zone_id = "e69d9e8116a9787a7c36dc16f6195ae2"
