name: Build & Deploy
on:
  push:
    branches:
      - "main"
  repository_dispatch:

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present
        env:
          CI: true

      - name: Deploy
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}

  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs:
      - build-and-deploy
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

  smoke-test:
    name: k6 Test
    runs-on: ubuntu-latest
    needs:
      - build-and-deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: scripts/test.js
